import { getFirestoreStore } from '@shipwithai/core/firestore-store';
import type { AgentRunResult, AgentRunConfig } from '@shipwithai/core/types';
import {
  AUDIT_OUTPUT_TOOL,
  SEVERITY_ORDER,
  countFindingsBySeverity,
  groupFindingsBySeverity,
  type AuditReport,
} from './audit-types';

function renderMarkdown(report: AuditReport, repoName?: string): string {
  const date = new Date().toISOString().slice(0, 10);
  const lines: string[] = [];
  lines.push('# Security Audit Report');
  lines.push('');
  if (repoName) lines.push(`**Target:** \`${repoName}\``);
  lines.push(`**Date:** ${date}`);
  lines.push(`**Auditor:** ShipWithAI Solidity Auditor`);
  lines.push('');
  lines.push('## Summary');
  lines.push(report.summary);
  lines.push('');
  lines.push(`**Recommendation:** ${report.recommendation.toUpperCase()}`);
  lines.push('');

  if (report.contractsReviewed?.length) {
    lines.push('## Contracts Reviewed');
    for (const c of report.contractsReviewed) lines.push(`- \`${c}\``);
    lines.push('');
  }

  const bySeverity = groupFindingsBySeverity(report.findings);

  lines.push(`## Findings (${report.findings.length})`);
  lines.push('');
  if (report.findings.length === 0) {
    lines.push('_No findings._');
    lines.push('');
  }

  for (const sev of SEVERITY_ORDER) {
    const items = bySeverity.get(sev);
    if (!items?.length) continue;
    lines.push(`### ${sev.charAt(0).toUpperCase() + sev.slice(1)} (${items.length})`);
    lines.push('');
    for (const f of items) {
      lines.push(`#### [${f.id}] ${f.title}`);
      if (f.location) lines.push(`**Location:** \`${f.location}\``);
      lines.push('');
      lines.push(f.description);
      if (f.recommendation) {
        lines.push('');
        lines.push(`**Recommendation:** ${f.recommendation}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('_This report was generated by an AI auditor. Human review is recommended before acting on these findings._');

  return lines.join('\n');
}

function findLastOutputToolCall(
  result: AgentRunResult,
  outputTool: string,
): AuditReport | null {
  for (let i = result.toolCallsLog.length - 1; i >= 0; i--) {
    const call = result.toolCallsLog[i];
    if (call.toolName === outputTool && !call.isError) {
      return call.input as unknown as AuditReport;
    }
  }
  return null;
}

export interface PersistedAuditReport {
  deliverableId: string;
  pdfUrl: string;
  downloadUrl: string;
}

/**
 * If the solidity-auditor called `submit_audit_report`, persist it as a Deliverable
 * (structured JSON + rendered markdown). Best-effort: failures are logged but never
 * break the invocation response. Returns the persisted identifiers so the UI can
 * surface download/PDF links, or null if nothing was persisted.
 */
export async function persistAuditReport(
  runConfig: AgentRunConfig,
  result: AgentRunResult,
): Promise<PersistedAuditReport | null> {
  if (runConfig.agentId !== 'solidity-auditor') return null;
  const report = findLastOutputToolCall(result, AUDIT_OUTPUT_TOOL);
  if (!report) return null;

  try {
    const store = getFirestoreStore();
    const markdown = renderMarkdown(report, runConfig.repoFullName);
    const counts = countFindingsBySeverity(report.findings);
    const severityLine = SEVERITY_ORDER
      .filter((s) => counts[s])
      .map((s) => `${counts[s]} ${s}`)
      .join(', ') || 'no findings';
    const title = `Security Audit — ${runConfig.repoFullName ?? 'contracts'}`;
    const description = `${report.recommendation.toUpperCase()} — ${severityLine}`;

    const deliverable = await store.saveDeliverable({
      type: 'audit_report',
      title,
      description,
      producedBy: 'solidity-auditor',
      sessionId: runConfig.sessionId,
      projectId: runConfig.projectId,
      preview: report.summary.slice(0, 280),
      downloadUrl: undefined,
    });

    const downloadUrl = `/api/deliverables/${deliverable.id}/download`;
    const pdfUrl = `/api/deliverables/${deliverable.id}/pdf`;

    await Promise.all([
      store.saveDeliverableContent({
        deliverableId: deliverable.id,
        content: markdown,
        contentType: 'text/markdown',
        fileName: 'audit-report.md',
      }),
      store.saveDeliverableContent({
        deliverableId: deliverable.id,
        content: JSON.stringify(report),
        contentType: 'application/json',
        fileName: 'audit-report.json',
      }, 'structured'),
      store.saveDeliverable({ ...deliverable, downloadUrl }),
    ]);

    return { deliverableId: deliverable.id, downloadUrl, pdfUrl };
  } catch (err) {
    console.error('[invoke] persistAuditReport failed', err);
    return null;
  }
}
